"""Tests for handoff.py — output format, graph counts, file write.

Verifies that generate_handoff() and write_handoff():
  - Return valid markdown with the expected sections
  - Handle None graph_storage gracefully
  - Count nodes/edges from a real NetworkX graph
  - Embed orchestrator cycle summary when provided
  - Write to the correct file path
  - Handle empty state (no papers ingested, no cache entries)
"""
import json
import tempfile
from pathlib import Path

import networkx as nx
import pytest

from src.agents.handoff import (
    _count_graph,
    _format_pmcid_list,
    _ingest_stats,
    generate_handoff,
    write_handoff,
)
from src.graph.networkx_json_storage import NetworkXJSONStorage


class TestCountGraph:
    def test_none_graph(self):
        assert _count_graph(None) == {"nodes": 0, "edges": 0}

    def test_real_graph_counts(self):
        gs = NetworkXJSONStorage(file_path="/tmp/_test_handoff_count.json")
        gs.add_node("mat:Ti", "material", {"name": "Titanium"})
        gs.add_node("cell:MSC", "cell_type", {"name": "MSC"})
        gs.add_edge("mat:Ti", "cell:MSC", "co_occurs_with", {
            "extracted_at": "2026-01-01T00:00:00Z",
            "source_paper": "test",
            "evidence_phrase": "Ti promotes MSC adhesion",
        })
        counts = _count_graph(gs)
        assert counts["nodes"] == 2
        assert counts["edges"] == 1


class TestFormatPmcidList:
    def test_empty(self):
        assert _format_pmcid_list([]) == "none"

    def test_few(self):
        result = _format_pmcid_list(["PMC123", "PMC456"])
        assert "PMC123" in result
        assert "PMC456" in result

    def test_many_with_overflow(self):
        pmcids = [f"PMC{i}" for i in range(20)]
        result = _format_pmcid_list(pmcids, limit=10)
        assert "+10 more" in result
        assert "PMC0" in result


class TestGenerateHandoff:
    def test_minimal_no_graph(self):
        content = generate_handoff(graph_storage=None)
        assert "# Federated RAG — System Handoff" in content
        assert "Knowledge Graph nodes" in content
        assert "| 0 " in content  # zero nodes

    def test_minimal_with_graph(self):
        gs = NetworkXJSONStorage(file_path="/tmp/_test_handoff_gen.json")
        # Clear any existing data
        gs._graph = nx.DiGraph()
        gs.add_node("mat:Ti", "material", {})
        gs.add_node("mat:TiO2", "material", {})
        gs.add_edge("mat:Ti", "mat:TiO2", "co_occurs_with", {
            "extracted_at": "2026-01-01T00:00:00Z",
            "source_paper": "test",
            "evidence_phrase": "test",
        })

        content = generate_handoff(graph_storage=gs)
        assert "| 2 " in content  # nodes
        assert "| 1 " in content  # edges

    def test_with_orchestrator_summary(self):
        summary = {
            "cycle": 3,
            "discovered_topics": 5,
            "epmc_queries_run": 4,
            "papers_fetched": 12,
            "papers_ingested": 3,
            "errors": ["kg_save: Permission denied"],
        }
        content = generate_handoff(
            graph_storage=None,
            orchestrator_summary=summary,
        )
        assert "## Latest Orchestrator Cycle" in content
        assert "Cycle: 3" in content
        assert "Discovered topics: 5" in content
        assert "Papers fetched: 12" in content
        assert "Papers ingested: 3" in content
        assert "kg_save: Permission denied" in content

    def test_markdown_sections_exist(self):
        content = generate_handoff(graph_storage=None)
        required_sections = [
            "# Federated RAG — System Handoff",
            "## System State",
            "## Ingested Paper IDs",
        ]
        for section in required_sections:
            assert section in content, f"Missing section: {section}"

    def test_auto_generated_footer(self):
        content = generate_handoff(graph_storage=None)
        assert "auto-generated by" in content
        assert "src/agents/handoff.py" in content


class TestWriteHandoff:
    def test_writes_to_default_path(self, tmp_path, monkeypatch):
        import src.agents.handoff as handoff_mod
        monkeypatch.setattr(handoff_mod, "HANDOFF_PATH", tmp_path / "HANDOFF.md")

        write_handoff(graph_storage=None)
        written = (tmp_path / "HANDOFF.md").read_text()
        assert "# Federated RAG" in written

    def test_writes_to_custom_path(self, tmp_path):
        custom = tmp_path / "custom_handoff.md"
        write_handoff(graph_storage=None, output_path=custom)
        assert custom.exists()
        content = custom.read_text()
        assert "# Federated RAG" in content


class TestIngestStatsHelper:
    """Verify _ingest_stats() returns a dict even when no progress file exists."""

    def test_returns_dict(self):
        stats = _ingest_stats()
        assert isinstance(stats, dict)
        assert "completed_count" in stats
        assert "completed" in stats
