"""
Handoff — auto-generate HANDOFF.md from the current system state.
Reads ingest progress, SPECTER2 cache stats, KG node/edge counts,
and orchestrator cycle summary to produce a structured markdown handoff
for the next instance.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

PROJECT_DIR = Path("projects/default")
HANDOFF_PATH = Path("HANDOFF.md")


def _count_graph(graph_storage: Any) -> Dict[str, int]:
    """Return node and edge counts from a graph storage instance."""
    counts = {"nodes": 0, "edges": 0}
    if graph_storage is None:
        return counts
    try:
        graph = getattr(graph_storage, "_graph", None)
        if graph is not None:
            counts["nodes"] = graph.number_of_nodes()
            counts["edges"] = graph.number_of_edges()
    except Exception:
        pass
    return counts


def _ingest_stats() -> Dict[str, Any]:
    """Return ingest progress stats."""
    try:
        from src.utils.ingest_progress import IngestProgress

        progress = IngestProgress()
        return {
            "completed_count": progress.completed_count(),
            "completed": sorted(progress.get_completed()) if progress.get_completed() else [],
        }
    except Exception:
        return {"completed_count": 0, "completed": []}


def _cache_stats() -> Dict[str, Any]:
    """Return SPECTER2 cache stats."""
    try:
        from src.utils.spector2_cache import Spector2Cache

        cache = Spector2Cache()
        return cache.stats()
    except Exception:
        return {"total_entries": 0, "with_embedding": 0}


def _format_pmcid_list(pmcids: list, limit: int = 10) -> str:
    """Format a PMCID list, showing first N with overflow count."""
    if not pmcids:
        return "none"
    shown = pmcids[:limit]
    lines = ", ".join(shown)
    if len(pmcids) > limit:
        lines += f" (+{len(pmcids) - limit} more)"
    return lines


def generate_handoff(
    *,
    graph_storage: Any = None,
    orchestrator_summary: Optional[Dict[str, Any]] = None,
) -> str:
    """Generate HANDOFF.md content from current system state.

    Args:
        graph_storage: Optional KG backend instance for node/edge counts.
        orchestrator_summary: Optional dict from ``Orchestrator._run_cycle()``.

    Returns:
        Full markdown string for writing to ``HANDOFF.md``.
    """
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    graph_counts = _count_graph(graph_storage)
    ingest = _ingest_stats()
    cache = _cache_stats()

    cycle_info = ""
    if orchestrator_summary:
        cycle_info = (
            f"## Latest Orchestrator Cycle\n\n"
            f"- Cycle: {orchestrator_summary.get('cycle', '?')}\n"
            f"- Discovered topics: {orchestrator_summary.get('discovered_topics', 0)}\n"
            f"- EPMC queries run: {orchestrator_summary.get('epmc_queries_run', 0)}\n"
            f"- Papers fetched: {orchestrator_summary.get('papers_fetched', 0)}\n"
            f"- Papers ingested: {orchestrator_summary.get('papers_ingested', 0)}\n"
        )
        errors = orchestrator_summary.get("errors", [])
        if errors:
            cycle_info += f"- Errors: {len(errors)}\n"
            for e in errors[:5]:
                cycle_info += f"  - `{e}`\n"

    content = (
        f"# Federated RAG — System Handoff\n\n"
        f"> Auto-generated {now}\n\n"
        f"## System State\n\n"
        f"| Component | Status |\n"
        f"|-----------|--------|\n"
        f"| Knowledge Graph nodes | {graph_counts['nodes']} |\n"
        f"| Knowledge Graph edges | {graph_counts['edges']} |\n"
        f"| Papers ingested (tracked) | {ingest['completed_count']} |\n"
        f"| SPECTER2 cache entries | {cache['total_entries']} |\n"
        f"| SPECTER2 with embeddings | {cache['with_embedding']} |\n\n"
        f"## Ingested Paper IDs\n\n"
        f"{_format_pmcid_list(ingest['completed'])}\n\n"
        f"{cycle_info}"
        f"---\n\n"
        f"*This file is auto-generated by ``src/agents/handoff.py``.*\n"
        f"*Last update: {now}*\n"
    )
    return content


def write_handoff(
    *,
    graph_storage: Any = None,
    orchestrator_summary: Optional[Dict[str, Any]] = None,
    output_path: Optional[Path | str] = None,
) -> None:
    """Generate and write HANDOFF.md to disk.

    Args:
        graph_storage: Optional KG backend for node/edge counts.
        orchestrator_summary: Optional dict from ``Orchestrator._run_cycle()``.
        output_path: Path to write (default: ``./HANDOFF.md``).
    """
    dest = Path(output_path) if output_path else HANDOFF_PATH
    dest.parent.mkdir(parents=True, exist_ok=True)
    content = generate_handoff(
        graph_storage=graph_storage,
        orchestrator_summary=orchestrator_summary,
    )
    dest.write_text(content, encoding="utf-8")
    logger.info("Handoff written to %s (%d bytes)", dest, len(content))
